### ISSUE TITLE
Implement X25519 encryption

### ISSUE THREAD

**Issue by msfjarvis** [android-password-store/kage#3]
There is a Curve25519 implementation in [WireGuard](https://github.com/WireGuard/wireguard-android/blob/master/tunnel/src/main/java/com/wireguard/crypto/Curve25519.java) that can probably be imported as-is after rewriting it in Kotlin

**Comment by Skrilltrax** [comment]
Closing this issue since we are gonna use [tink](https://github.com/google/tink) for all crypto stuff
